### ISSUE TITLE
Add support for nested gfxmenu components

### ISSUE THREAD

**Issue by max-ishere** [max-ishere/grub-theme#2]
# Relevant GRUB documentation

https://www.gnu.org/software/grub/manual/grub-dev/grub-dev.html#GUI-Components

> The GUI component instances are created by the theme loader in gfxmenu/theme_loader.c when a theme is loaded. Theme files specify statements such as ‘+vbox{ +label { text="Hello" } +label{ text="World" } }’ to add components to the component tree root. By nesting the component creation statements in the theme file, the instantiated components are nested the same way.

# TODO

- [ ] Refactor of the parsing code?
- [ ] Add a branch for either parse a component property or new nested component in the parser
- [ ] [Split this test](https://github.com/max-ishere/grub-theme/blob/761cc160b1930384be2abf478797832a7b11c705/src/parser/theme_txt.rs#L314-L316) into smaller tests for component and global property

# Related source files in this repo

[lib: parser/theme_txt.rs](https://github.com/max-ishere/grub-theme/blob/main/src/parser/theme_txt.rs)
[examples: theme_txt.rs](https://github.com/max-ishere/grub-theme/blob/main/examples/theme_txt.rs)

**Comment by max-ishere** [comment]
It seems not all components should support nested components, only the container types:

> Containers:
>
> - canvas
> - hbox
> - vbox

The other components should not allow such declarations.

> Components (non-container):
>
> - label
> - image
> - progress_bar
> - circular_progress
> - list (currently hard coded to be a boot menu list)

It would be nice to slightly adjust the implementation of the parser and have 2 stages (the first one already exists and the second one is currently in development, I haven't pushed it yet and it will likely be in a separate branch for now)

- Tokenizer
  This one will produce a token tree which is currently stored in a [`parser::theme_txt::Document`](https://github.com/max-ishere/grub-theme/blob/761cc160b1930384be2abf478797832a7b11c705/src/parser/theme_txt.rs#L54-L56).
- *I cant find the correct term for this one*
  Its job is to take a token tree and turn it from map<string, string> to Rusty structs that can be rendered. At this stage we can also decide if it's ok to have a nested component. The tokenizer would not care about that.
